spring:
  mvc:
    dispatch-options-request: true
  datasource:
    url: jdbc:mysql://localhost/springbootdb
    username: mysql
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate: # Tells spring what to do at the app startup
      ddl-auto: update
    show-sql: true # visualize sql queries
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
